FROM node:18 AS builder

ARG REACT_APP_ADMIN_HOST
ARG REACT_APP_STRAPI_HOST
ARG REACT_APP_STRAPI_KEY
ARG REACT_APP_OPEN_TELEMETRY_SIGNOZ_URL
ARG REACT_APP_ENV

ENV REACT_APP_ADMIN_HOST $REACT_APP_ADMIN_HOST
ENV REACT_APP_STRAPI_HOST $REACT_APP_STRAPI_HOST
ENV REACT_APP_STRAPI_KEY $REACT_APP_STRAPI_KEY
ENV REACT_APP_OPEN_TELEMETRY_SIGNOZ_URL $REACT_APP_OPEN_TELEMETRY_SIGNOZ_URL
ENV REACT_APP_ENV $REACT_APP_ENV

COPY . /var/www/html/vitalflow/front
WORKDIR /var/www/html/vitalflow/front
RUN npm install && \
  npm run build

FROM node:18
ARG REACT_APP_ADMIN_HOST
ARG REACT_APP_STRAPI_HOST
ARG REACT_APP_STRAPI_KEY
ARG REACT_APP_OPEN_TELEMETRY_SIGNOZ_URL
ARG REACT_APP_ENV

ENV REACT_APP_ADMIN_HOST $REACT_APP_ADMIN_HOST
ENV REACT_APP_STRAPI_HOST $REACT_APP_STRAPI_HOST
ENV REACT_APP_STRAPI_KEY $REACT_APP_STRAPI_KEY
ENV REACT_APP_OPEN_TELEMETRY_SIGNOZ_URL $REACT_APP_OPEN_TELEMETRY_SIGNOZ_URL
ENV REACT_APP_ENV $REACT_APP_ENV

RUN npm install -g serve
WORKDIR /var/www/html/vitalflow/front
COPY --from=builder /var/www/html/vitalflow/front/package*.json ./
COPY --from=builder /var/www/html/vitalflow/front/build ./build
EXPOSE 3000
CMD ["serve", "-s", "build", "-l", "3000"]
