/**
 * Consultation Mode Type Definitions
 *
 * Types for real-time clinician-patient consultation sessions,
 * including annotations, communication, and session recording.
 *
 * @module types/consultation
 */

import type { PostureSession, TreatmentGoal } from './posture';

/**
 * Consultation session status
 */
export type ConsultationStatus =
	| 'idle' // Not started
	| 'connecting' // Establishing connection
	| 'active' // Session in progress
	| 'paused' // Temporarily paused
	| 'ended' // Session completed
	| 'error'; // Connection error

/**
 * Consultation participant role
 */
export type ParticipantRole = 'clinician' | 'patient';

/**
 * Annotation tool type
 */
export type AnnotationTool =
	| 'pen'
	| 'highlighter'
	| 'eraser'
	| 'arrow'
	| 'circle'
	| 'text';

/**
 * Annotation stroke style
 */
export interface AnnotationStroke {
	/** Tool used for this stroke */
	tool: AnnotationTool;

	/** Color (hex format) */
	color: string;

	/** Line width in pixels */
	width: number;

	/** Opacity (0-1) */
	opacity: number;

	/** Drawing points (normalized 0-1 coordinates) */
	points: Array<{ x: number; y: number }>;

	/** Timestamp of creation */
	timestamp: number;

	/** Creator's participant ID */
	participantId: string;
}

/**
 * Annotation layer for a posture scan image
 */
export interface AnnotationLayer {
	/** Layer identifier */
	id: string;

	/** Associated session ID */
	sessionId: string;

	/** Image identifier (front/side/back view) */
	imageId: string;

	/** All annotation strokes on this layer */
	strokes: AnnotationStroke[];

	/** Layer creation timestamp */
	createdAt: string;

	/** Last modified timestamp */
	modifiedAt: string;
}

/**
 * Chat message
 */
export interface ChatMessage {
	/** Message identifier */
	id: string;

	/** Sender participant ID */
	participantId: string;

	/** Sender role */
	role: ParticipantRole;

	/** Message content */
	content: string;

	/** Timestamp (ISO 8601) */
	timestamp: string;

	/** Message type */
	type: 'text' | 'system';
}

/**
 * Real-time communication channel status
 */
export interface CommunicationChannel {
	/** Voice channel active */
	voice: boolean;

	/** Video channel active */
	video: boolean;

	/** Screen sharing active */
	screenShare: boolean;

	/** Text chat active */
	chat: boolean;

	/** Connection quality (0-100) */
	quality: number;
}

/**
 * Consultation participant
 */
export interface ConsultationParticipant {
	/** Participant identifier */
	id: string;

	/** User ID */
	userId: string;

	/** Display name */
	name: string;

	/** Role in consultation */
	role: ParticipantRole;

	/** Connection status */
	connected: boolean;

	/** Join timestamp */
	joinedAt: string;

	/** Active communication channels */
	channels: CommunicationChannel;
}

/**
 * Collaborative goal setting entry
 */
export interface CollaborativeGoal extends TreatmentGoal {
	/** Who proposed this goal */
	proposedBy: ParticipantRole;

	/** Agreement status */
	agreed: boolean;

	/** Patient's priority level (1-5) */
	patientPriority?: number;

	/** Clinician's recommended priority (1-5) */
	clinicianPriority?: number;

	/** Discussion notes */
	notes?: string;
}

/**
 * Session summary section
 */
export interface SessionSummarySection {
	/** Section title */
	title: string;

	/** Section content (markdown supported) */
	content: string;

	/** Auto-generated by AI */
	aiGenerated: boolean;
}

/**
 * Consultation session recording metadata
 */
export interface SessionRecording {
	/** Recording identifier */
	id: string;

	/** Consultation session ID */
	consultationId: string;

	/** Recording start time */
	startTime: string;

	/** Recording end time */
	endTime: string;

	/** Duration in seconds */
	duration: number;

	/** Storage location (encrypted URL) */
	storageUrl: string;

	/** File size in bytes */
	fileSize: number;

	/** HIPAA compliance metadata */
	compliance: {
		/** Encryption algorithm used */
		encryption: string;

		/** Access log enabled */
		accessLogged: boolean;

		/** Retention policy (days) */
		retentionDays: number;

		/** Auto-deletion date */
		deletionDate: string;
	};
}

/**
 * Main consultation session state
 */
export interface ConsultationSession {
	/** Session identifier */
	id: string;

	/** Session status */
	status: ConsultationStatus;

	/** Participants in session */
	participants: ConsultationParticipant[];

	/** Associated posture session being reviewed */
	postureSessionId: string;

	/** Posture session data */
	postureSession?: PostureSession;

	/** Comparison session (baseline) if available */
	comparisonSessionId?: string;

	/** Annotation layers */
	annotations: AnnotationLayer[];

	/** Chat messages */
	chatMessages: ChatMessage[];

	/** Collaborative goals being discussed */
	goals: CollaborativeGoal[];

	/** Session recording metadata */
	recording?: SessionRecording;

	/** Session start time */
	startTime: string;

	/** Session end time (null if active) */
	endTime: string | null;

	/** Session summary (generated at end) */
	summary?: {
		/** Summary sections */
		sections: SessionSummarySection[];

		/** Key decisions made */
		decisions: string[];

		/** Action items */
		actionItems: string[];

		/** Next appointment date */
		nextAppointment?: string;
	};

	/** Display settings */
	displaySettings: {
		/** Mirror patient view for projection */
		mirrorMode: boolean;

		/** Dual-view layout active */
		dualView: boolean;

		/** AirPlay/Chromecast connected */
		externalDisplay: boolean;
	};
}

/**
 * WebSocket message types for real-time sync
 */
export type ConsultationMessageType =
	| 'annotation:add'
	| 'annotation:update'
	| 'annotation:delete'
	| 'chat:message'
	| 'participant:joined'
	| 'participant:left'
	| 'channel:update'
	| 'goal:propose'
	| 'goal:update'
	| 'session:pause'
	| 'session:resume'
	| 'session:end';

/**
 * WebSocket message payload
 */
export interface ConsultationMessage {
	/** Message type */
	type: ConsultationMessageType;

	/** Session ID */
	sessionId: string;

	/** Message payload */
	payload: unknown;

	/** Timestamp */
	timestamp: number;

	/** Sender participant ID */
	senderId: string;
}

/**
 * Consultation mode preferences
 */
export interface ConsultationPreferences {
	/** Default annotation tool */
	defaultTool: AnnotationTool;

	/** Default annotation color */
	defaultColor: string;

	/** Default stroke width */
	defaultStrokeWidth: number;

	/** Enable auto-save annotations */
	autoSave: boolean;

	/** Auto-save interval (seconds) */
	autoSaveInterval: number;

	/** Enable session recording by default */
	autoRecord: boolean;

	/** Email summary to patient after session */
	emailSummary: boolean;

	/** Show patient view mirror on external display */
	externalDisplayMirror: boolean;
}
