/**
 * Dashboard Alert System - Type Definitions
 * EPIC-014-S1: Alert Rule Data Structure
 *
 * Defines the core types for the dashboard alert and notification system,
 * including alert types, priority levels, alert objects, and rule definitions.
 *
 * @module stores/dashboard/alertTypes
 */

import { ReduxState } from '@stores/index';

// ============================================================================
// ALERT TYPE ENUM
// ============================================================================

/**
 * AlertType Enum
 *
 * Defines all possible alert categories that can appear on the dashboard.
 * Each type maps to specific user actions, program states, or system events.
 *
 * @enum {string}
 *
 * @example
 * ```typescript
 * const alert: DashboardAlert = {
 *   type: AlertType.AssessmentDue,
 *   // ... other properties
 * };
 * ```
 */
export enum AlertType {
	/**
	 * Assessment Due Alert
	 * Triggered when a scheduled assessment (ROM, posture, survey) is overdue
	 * or approaching its due date.
	 */
	AssessmentDue = 'assessment-due',

	/**
	 * Program Expiring Alert
	 * Triggered when an active program is nearing completion or expiration.
	 * Helps users stay on track with their rehabilitation schedule.
	 */
	ProgramExpiring = 'program-expiring',

	/**
	 * Milestone Reached Alert
	 * Triggered when user achieves a significant milestone (e.g., 10 sessions,
	 * 30-day streak, ROM improvement threshold).
	 */
	MilestoneReached = 'milestone-reached',

	/**
	 * Streak At Risk Alert
	 * Triggered when user's current activity streak is at risk of breaking
	 * (e.g., no activity in 18+ hours, approaching 24-hour deadline).
	 */
	StreakAtRisk = 'streak-at-risk',

	/**
	 * New Recommendation Alert
	 * Triggered when system generates new personalized recommendations based on
	 * user's progress, assessment results, or historical data.
	 */
	NewRecommendation = 'new-recommendation',
}

// ============================================================================
// PRIORITY ENUM
// ============================================================================

/**
 * AlertPriority Enum
 *
 * Defines numeric priority levels for alerts. Higher numbers indicate higher priority.
 * Priority determines visual treatment, placement, and dismissibility.
 *
 * Scale: 1 (Low) → 5 (Medium) → 10 (High/Critical)
 *
 * @enum {number}
 *
 * @example
 * ```typescript
 * // High priority alert (cannot be dismissed, shown prominently)
 * const criticalAlert: DashboardAlert = {
 *   priority: AlertPriority.High,
 *   dismissible: false,
 *   // ... other properties
 * };
 *
 * // Low priority alert (can be dismissed, shown below fold)
 * const infoAlert: DashboardAlert = {
 *   priority: AlertPriority.Low,
 *   dismissible: true,
 *   // ... other properties
 * };
 * ```
 */
export enum AlertPriority {
	/**
	 * Low Priority (1)
	 * Informational alerts, tips, non-urgent recommendations.
	 * Can be dismissed by user, shown below fold.
	 */
	Low = 1,

	/**
	 * Medium Priority (5)
	 * Important but not urgent alerts, upcoming deadlines, reminders.
	 * Can be dismissed, shown above fold.
	 */
	Medium = 5,

	/**
	 * High Priority (10)
	 * Critical alerts, overdue items, streak breaks, urgent actions required.
	 * Cannot be dismissed until action taken, shown prominently at top.
	 */
	High = 10,
}

// ============================================================================
// DASHBOARD ALERT INTERFACE
// ============================================================================

/**
 * DashboardAlert Interface
 *
 * Represents a single alert/notification displayed on the patient dashboard.
 * Alerts are generated by rules and displayed to prompt user action.
 *
 * @interface DashboardAlert
 *
 * @property {string} id - Unique identifier for this alert instance (UUID recommended)
 * @property {AlertType} type - Category of alert (assessment-due, milestone, etc.)
 * @property {AlertPriority} priority - Numeric priority level (1=Low, 5=Medium, 10=High)
 * @property {string} title - Short, bold headline for the alert (max ~50 chars)
 * @property {string} message - Detailed explanation of the alert (max ~200 chars)
 * @property {string} [actionLabel] - Optional CTA button text (e.g., "Complete Assessment")
 * @property {string} [actionUrl] - Optional URL/route for CTA button navigation
 * @property {boolean} dismissible - Whether user can manually dismiss this alert
 * @property {Date} createdAt - Timestamp when alert was generated
 * @property {'success' | 'info' | 'warning' | 'error'} variant - Visual style (maps to Ant Design Alert)
 *
 * @example
 * ```typescript
 * const alert: DashboardAlert = {
 *   id: 'alert-123e4567-e89b-12d3',
 *   type: AlertType.AssessmentDue,
 *   priority: AlertPriority.Medium,
 *   title: 'Weekly ROM Assessment Due',
 *   message: 'Your scheduled ROM assessment is due today. Complete it to track your progress.',
 *   actionLabel: 'Start Assessment',
 *   actionUrl: '/rom/start-scan',
 *   dismissible: true,
 *   createdAt: new Date(),
 *   variant: 'info',
 * };
 * ```
 */
export interface DashboardAlert {
	/** Unique identifier (UUID recommended) */
	id: string;

	/** Category of alert */
	type: AlertType;

	/** Numeric priority (1=Low, 5=Medium, 10=High) */
	priority: AlertPriority;

	/** Short headline (max ~50 chars) */
	title: string;

	/** Detailed message (max ~200 chars) */
	message: string;

	/** Optional CTA button text */
	actionLabel?: string;

	/** Optional CTA button URL/route */
	actionUrl?: string;

	/** Whether user can dismiss this alert */
	dismissible: boolean;

	/** Timestamp when alert was generated */
	createdAt: Date;

	/** Visual style (maps to Ant Design Alert component) */
	variant: 'success' | 'info' | 'warning' | 'error';
}

// ============================================================================
// ALERT RULE INTERFACE
// ============================================================================

/**
 * AlertRule Interface
 *
 * Defines a rule for generating alerts based on Redux state conditions.
 * Rules are evaluated on state changes to determine if alerts should be shown.
 *
 * @interface AlertRule
 *
 * @property {string} id - Unique identifier for this rule (e.g., 'rule-assessment-due')
 * @property {AlertType} type - Type of alert this rule generates
 * @property {AlertPriority} priority - Default priority for alerts from this rule
 * @property {Function} condition - Evaluates Redux state, returns true if alert should show
 * @property {Function} generateAlert - Generates alert object when condition is true
 *
 * @example
 * ```typescript
 * const assessmentDueRule: AlertRule = {
 *   id: 'rule-assessment-due',
 *   type: AlertType.AssessmentDue,
 *   priority: AlertPriority.Medium,
 *   condition: (state: ReduxState) => {
 *     const lastAssessment = state.rom.sessions[0];
 *     if (!lastAssessment) return true; // Never assessed
 *     const daysSince = daysBetween(lastAssessment.createdAt, new Date());
 *     return daysSince >= 7; // Weekly assessment due
 *   },
 *   generateAlert: (state: ReduxState) => ({
 *     type: AlertType.AssessmentDue,
 *     priority: AlertPriority.Medium,
 *     title: 'Weekly ROM Assessment Due',
 *     message: 'Complete your assessment to track progress.',
 *     actionLabel: 'Start Assessment',
 *     actionUrl: '/rom/start-scan',
 *     dismissible: true,
 *     variant: 'info',
 *   }),
 * };
 * ```
 */
export interface AlertRule {
	/** Unique identifier for this rule */
	id: string;

	/** Type of alert this rule generates */
	type: AlertType;

	/** Default priority for alerts from this rule */
	priority: AlertPriority;

	/**
	 * Condition function - evaluates Redux state
	 * @param state - Full Redux state object
	 * @returns true if alert should be shown, false otherwise
	 */
	condition: (state: ReduxState) => boolean;

	/**
	 * Alert generator function - creates alert object
	 * @param state - Full Redux state object
	 * @returns Partial alert object (id and createdAt added automatically)
	 */
	generateAlert: (state: ReduxState) => Omit<DashboardAlert, 'id' | 'createdAt'>;
}

// ============================================================================
// RULESET TYPE
// ============================================================================

/**
 * AlertRuleset Type
 *
 * Array of alert rules to be evaluated for the dashboard.
 * Rules are evaluated in order of priority (High → Medium → Low).
 *
 * @type {AlertRule[]}
 *
 * @example
 * ```typescript
 * const dashboardRules: AlertRuleset = [
 *   assessmentDueRule,
 *   streakAtRiskRule,
 *   milestoneReachedRule,
 * ];
 * ```
 */
export type AlertRuleset = AlertRule[];
