/**
 * Service Worker for Offline Support and Caching
 *
 * Story 4.3: Performance Optimization - AC5 (Caching Strategy)
 *
 * Implements:
 * - Offline capability with fallback responses
 * - API response caching with stale-while-revalidate
 * - Static asset caching with cache-first strategy
 * - Runtime caching for dynamic content
 *
 * @module service-worker
 */

/// <reference lib="webworker" />

import { clientsClaim } from 'workbox-core';
import { ExpirationPlugin } from 'workbox-expiration';
import {
	precacheAndRoute,
	createHandlerBoundToURL,
	type PrecacheEntry,
} from 'workbox-precaching';
import { registerRoute } from 'workbox-routing';
import {
	StaleWhileRevalidate,
	CacheFirst,
	NetworkFirst,
} from 'workbox-strategies';

// Extend ServiceWorkerGlobalScope to include Workbox types
declare const self: ServiceWorkerGlobalScope & {
	__WB_MANIFEST: (PrecacheEntry | string)[];
};

// Take control of all clients immediately
clientsClaim();

// Precache all assets generated by the build process
// This includes the app shell (HTML, CSS, JS)
precacheAndRoute(self.__WB_MANIFEST);

// Set up App Shell-style routing for SPA navigation
// This allows the app to work offline for all routes
const fileExtensionRegexp = /\/[^/?]+\.[^/]+$/;
registerRoute(
	({ request, url }: { request: Request; url: URL }) => {
		// Skip cross-origin requests
		if (request.mode !== 'navigate') {
			return false;
		}

		// Skip URLs with file extensions
		if (url.pathname.match(fileExtensionRegexp)) {
			return false;
		}

		return true;
	},
	createHandlerBoundToURL(process.env.PUBLIC_URL + '/index.html'),
);

// Cache the Google Fonts stylesheets with a stale-while-revalidate strategy
registerRoute(
	({ url }) => url.origin === 'https://fonts.googleapis.com',
	new StaleWhileRevalidate({
		cacheName: 'google-fonts-stylesheets',
	}),
);

// Cache the underlying font files with a cache-first strategy for 1 year
registerRoute(
	({ url }) => url.origin === 'https://fonts.gstatic.com',
	new CacheFirst({
		cacheName: 'google-fonts-webfonts',
		plugins: [
			new ExpirationPlugin({
				maxAgeSeconds: 60 * 60 * 24 * 365, // 1 year
				maxEntries: 30,
			}),
		],
	}),
);

// Cache images with a cache-first strategy
registerRoute(
	({ request }) => request.destination === 'image',
	new CacheFirst({
		cacheName: 'images',
		plugins: [
			new ExpirationPlugin({
				maxEntries: 60,
				maxAgeSeconds: 30 * 24 * 60 * 60, // 30 Days
			}),
		],
	}),
);

// Cache API responses with stale-while-revalidate (Story 4.3: AC5)
// This provides instant response from cache while fetching fresh data in background
registerRoute(
	({ url }) => url.pathname.startsWith('/api/'),
	new StaleWhileRevalidate({
		cacheName: 'api-cache',
		plugins: [
			new ExpirationPlugin({
				maxEntries: 50,
				maxAgeSeconds: 5 * 60, // 5 minutes
			}),
		],
	}),
);

// Cache Strapi CMS content with network-first strategy
// Falls back to cache if network is unavailable
registerRoute(
	({ url }) =>
		url.hostname === 'strapi.vitalflow.ai' || url.pathname.includes('/strapi/'),
	new NetworkFirst({
		cacheName: 'strapi-content',
		plugins: [
			new ExpirationPlugin({
				maxEntries: 100,
				maxAgeSeconds: 24 * 60 * 60, // 24 hours
			}),
		],
	}),
);

// Cache static assets (JS, CSS) with cache-first strategy
registerRoute(
	({ request }) =>
		request.destination === 'script' || request.destination === 'style',
	new CacheFirst({
		cacheName: 'static-resources',
		plugins: [
			new ExpirationPlugin({
				maxEntries: 100,
				maxAgeSeconds: 24 * 60 * 60, // 24 hours
			}),
		],
	}),
);

// Listen for skip waiting message
self.addEventListener('message', event => {
	if (event.data && event.data.type === 'SKIP_WAITING') {
		self.skipWaiting();
	}
});

// Log service worker registration
self.addEventListener('install', _event => {});

self.addEventListener('activate', _event => {});

// Export empty object to make this a module
export {};
